language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build
  - cp -R ./dist ./demo-dist
  - npm run build-bundle

deploy:
  - provider: npm
    email: $NPM_API_EMAIL
    api_key: $NPM_API_TOKEN
    skip-cleanup: true
    on:
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    target-branch: gh-pages
    local-dir: demo-dist
    on:
      tags: true
